### ISSUE TITLE
Bug with coloring

### ISSUE THREAD

**Issue by vsheg** [molstar/VSCoding-Sequence#15]
Hello, I have found a bug: color scale is reversed 
![Screenshot 2022-11-01 at 19 01 59](https://user-images.githubusercontent.com/36817377/199280840-984f95c7-1508-42f3-9e35-b107845d94e4.jpg)

**Comment by a-r-j** [comment]
Thanks for the heads up. I'll bump the version which should resolve it!

**Comment by a-r-j** [comment]
Hey @vsheg has this been resolved for you now?

**Comment by vsheg** [comment]
@a-r-j looks good, thanks!
