### ISSUE TITLE
Cannot start protein viewer 

### ISSUE THREAD

**Issue by dangthatsright** [molstar/VSCoding-Sequence#22]
Hello, I really enjoy using Protein Viewer but I think there must be something incompatible in the latest version of VSCode. I try launching from file but nothing happens. I starting from the command palette and it says `command 'protein-viewer.start' not found`. I was wondering what is the suggested fix for this. thanks!

**Comment by a-r-j** [comment]
Hi @dangthatsright I'm struggling to reproduce this with version 0.1.0 on VSCode 1.74.2.

However, I think the problem is that launching from file is supported via right-clicking on the file in the explorer panel (rather than via the command palette).

I think this may be related to #10

**Comment by dangthatsright** [comment]
Oh I was on 1.64 something and it seems like updating to 1.74.2 did the trick! It is very strange because it was working before and recently it wasn't working and I don't think I updated anything. Welp, not sure if it's worth debugging anymore. Thanks for the help!
