### ISSUE TITLE
Bond breaking/forming is no longer happening 

### ISSUE THREAD

**Issue by hekima31** [molstar/VSCoding-Sequence#23]
Hiya 👋,
Thanks very much for this fantastic tool! It's enhanced my workflow significantly. I recently noticed that my trajectory files don't show bond breaking/forming. Instead bonds stretch unreasonably (See screenshot of XYZ file)
![image](https://user-images.githubusercontent.com/55980431/216351914-32ee256a-3631-49da-aa0f-27e1852c2f33.png)

**Comment by a-r-j** [comment]
Hi @hekima31 

I think this should be posted over in the [molstar main project](https://github.com/molstar/molstar).

As a quick triage to see if this has been resolved & there's a version issue, what happens if you open this trajectory here: https://molstar.org/viewer/

**Comment by hekima31** [comment]
Hi @a-r-j,
Tried it and get the same issue as above. What I noticed is that it only started happening a few months ago. I will go ahead and post this on the main project too.

**Comment by hekima31** [comment]
Just confirming this is fixed by turning dynamic bonds on (screenshot). Thank you!
![image](https://user-images.githubusercontent.com/55980431/217172823-b6a503d8-0688-4785-a080-fb798c75a897.png)
