### ISSUE TITLE
WebGL does not seem to be available issue

### ISSUE THREAD

**Issue by sirius777coder** [molstar/VSCoding-Sequence#29]
Hi, I tried to open a pdb file using ProteinViewer as usual but failed. I'm not sure if it's because of my Chrome version. This issue is new to me.

> WebGL does not seem to be available. This can be caused by an outdated browser, graphics card driver issue, or bad weather. Sometimes, just restarting the browser helps. Also, make sure hardware acceleration is enabled in your browser.

![image](https://github.com/molstar/VSCoding-Sequence/assets/72984163/02171c35-7f11-4d90-b5b0-25a5c60130ff)

**Comment by a-r-j** [comment]
Hi @sirius777coder 

Sorry, I'm not really sure how to debug this. Did you make any progress?

**Comment by sirius777coder** [comment]
Actually I uninstall and install VScode several times and it work😅
