### ISSUE TITLE
Question: is it possible to load an xtc file along with a topology file from e.g. pdb?

### ISSUE THREAD

**Issue by shuzhewang-iso** [molstar/VSCoding-Sequence#33]
Generally how could I load a trajectory? can I have a binary xtc file for the traj loaded alongside a single frame of pdb?

**Comment by a-r-j** [comment]
Hi @shuzhewang-iso 

Yes, this is possible. You need to do it though the viewer (see screenshot); I've not added appropriate VSCode bindings for this (PR welcome if you'd like to take it on!).
<img width="336" alt="Screenshot 2024-08-23 at 12 21 37" src="https://github.com/user-attachments/assets/e7b4005b-5ea0-4197-9940-239241fdd856">

**Comment by shuzhewang-iso** [comment]
Thank you!
