### ISSUE TITLE
WebGL does not seem to be available.

### ISSUE THREAD

**Issue by ParthBibekar** [molstar/VSCoding-Sequence#35]
Opening any PDB shows the following error. I am not sure how to debug this

![image](https://github.com/user-attachments/assets/f2e9bc18-53ab-4730-8817-2e01856844e2)

**Comment by a-r-j** [comment]
Hi @ParthBibeka,

It's not much to go on but this has been encountered before: https://github.com/molstar/VSCoding-Sequence/issues/29

**Comment by ParthBibekar** [comment]
Hi, I installed version 0.0.2 and it works well, I don't know what changed for later versions

**Comment by ParthBibekar** [comment]
It seems that upto v0.0.7 it works for me. Perhaps the issue is with `Mol* >=3.0.2` 

Here are some details of my setup:

```
VS code version: 1.94.2
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Linux x64 6.8.0-45-generic snap
```

**Comment by a-r-j** [comment]
Great, glad it worked out. Unfortunately I don't have bandwidth to dig into this further. Thanks for sharing your findings!
