### ISSUE TITLE
The wrong PDB is opened

### ISSUE THREAD

**Issue by FlorisLoffler** [molstar/VSCoding-Sequence#37]
When I try to open the file https://www.rcsb.org/structure/3nty , so 3NTY, it instead opens 1TQN. I can't change this anywhere, and the fact that protein viewer also doesn't have any adjustable settings makes this harder to solve.

**Comment by a-r-j** [comment]
Hi @FlorisLoffler I'm struggling to reproduce this behaviour. How are you launching the viewer? Are you using the command palette or right-clicking on the PDB file?
