### ISSUE TITLE
Adding/Removing/Selecting Atoms from XYZ File

### ISSUE THREAD

**Issue by jamesETsmith** [molstar/VSCoding-Sequence#9]
Hi @a-r-j, thanks for this VSCode extension! I've found that I can't select a single atom when I load an xyz file. Is there a way to do this in the VSCoding-Sequence? Similarly, can you add and delete single atoms or display their coordinates?

Thanks!

**Comment by a-r-j** [comment]
Hey @jamesETsmith glad you like it :) Could you share an example file I can take a look at?

**Comment by jamesETsmith** [comment]
Sure thing! Here it is:
[h2o_25.xyz.txt](https://github.com/molstar/VSCoding-Sequence/files/8535006/h2o_25.xyz.txt)

**Comment by a-r-j** [comment]
If you click the Selection Mode icon in the toggle menu you can select individual atoms (cursor icon) if you change the selection mode to Atom/coarse (a bar will appear at the top of the canvas, the default is Residue)

![https://camo.githubusercontent.com/f368f91fe3c9ef9dfc8ae788eae90b2d369d497d6f3b13a857fddc01327c3dc7/68747470733a2f2f6d6f6c737461722e6f72672f7669657765722d646f63732f696d672f67656e6572616c696e74657266616365332e706e67]


Wrt deleting and showing coordinates, I'm not exactly sure - you can ask over at the [main Mol* repo](https://github.com/molstar/molstar/issues). One possible solution is defining a new component with a selection and just visualising that.

**Comment by arose** [comment]
Mol* doesn't support editing but you can hide atoms from display. There is no way to display an atoms coordinates at the moment.

**Comment by jamesETsmith** [comment]
Thanks for the help @a-r-j and @arose!
